config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :administrators

  post 'security/login'

  post 'security/logout'

  get 'security/index'

  resources :sale_details

  resources :sales

  resources :foods

  resources :food_types

  resources :clients

  resources :waiters

  resources :chefs

  resources :people

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  belongs_to :person
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  belongs_to :person
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :person
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :administrator
  has_one :client
  has_one :chef
  has_one :waiter
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
  belongs_to :person
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]

  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
  end

  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # GET /chefs/1/edit
  def edit
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(chef_params)

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @chef, notice: 'Chef was successfully created.' }
        format.json { render :show, status: :created, location: @chef }
      else
        format.html { render :new }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chefs/1
  # PATCH/PUT /chefs/1.json
  def update
    respond_to do |format|
      if @chef.update(chef_params)
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { render :show, status: :ok, location: @chef }
      else
        format.html { render :edit }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef.destroy
    respond_to do |format|
      format.html { redirect_to chefs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef
      @chef = Chef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chef_params
      params.require(:chef).permit(:person_id, :cooked, :salary)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food_type_id, :noun, :description, :cost)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client_id, :waiter_id, :total_cost, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/security_helper.rb
module SecurityHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chefs/_form.html.erb
<%= form_for(@chef) do |f| %>
  <% if @chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chef.errors.count, "error") %> prohibited this chef from being saved:</h2>

      <ul>
      <% @chef.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :cooked %><br>
    <%= f.text_field :cooked %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chefs/edit.html.erb
<h1>Editing chef</h1>

<%= render 'form' %>

<%= link_to 'Show', @chef %> |
<%= link_to 'Back', chefs_path %>

app/views/chefs/index.html.erb
<h1>Listing chefs</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Cooked</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chefs.each do |chef| %>
      <tr>
        <td><%= chef.person_id %></td>
        <td><%= chef.cooked %></td>
        <td><%= chef.salary %></td>
        <td><%= link_to 'Show', chef %></td>
        <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
        <td><%= link_to 'Destroy', chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chef', new_chef_path %>

app/views/chefs/new.html.erb
<h1>New chef</h1>

<%= render 'form' %>

<%= link_to 'Back', chefs_path %>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @chef.person_id %>
</p>

<p>
  <strong>Cooked:</strong>
  <%= @chef.cooked %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @chef.salary %>
</p>

<%= link_to 'Edit', edit_chef_path(@chef) %> |
<%= link_to 'Back', chefs_path %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :waiter_id %><br>
    <%= f.number_field :waiter_id %>
  </div>
  <div class="field">
    <%= f.label :total_cost %><br>
    <%= f.text_field :total_cost %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Waiter</th>
      <th>Total cost</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.client_id %></td>
        <td><%= sale.waiter_id %></td>
        <td><%= sale.total_cost %></td>
        <td><%= sale.state %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @sale.client_id %>
</p>

<p>
  <strong>Waiter:</strong>
  <%= @sale.waiter_id %>
</p>

<p>
  <strong>Total cost:</strong>
  <%= @sale.total_cost %>
</p>

<p>
  <strong>State:</strong>
  <%= @sale.state %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>