config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :administrators

  post 'security/login'

  post 'security/logout'

  get 'security/index'

  resources :sale_details

  resources :sales

  resources :foods

  resources :food_types

  resources :clients

  resources :waiters

  resources :chefs

  resources :people

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  belongs_to :person
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  belongs_to :person
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :person
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :administrator
  has_one :client
  has_one :chef
  has_one :waiter
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
  belongs_to :person
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:show, :edit, :update, :destroy]

  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
  end

  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # GET /chefs/1/edit
  def edit
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(chef_params)

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @chef, notice: 'Chef was successfully created.' }
        format.json { render :show, status: :created, location: @chef }
      else
        format.html { render :new }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chefs/1
  # PATCH/PUT /chefs/1.json
  def update
    respond_to do |format|
      if @chef.update(chef_params)
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { render :show, status: :ok, location: @chef }
      else
        format.html { render :edit }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef.destroy
    respond_to do |format|
      format.html { redirect_to chefs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef
      @chef = Chef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chef_params
      params.require(:chef).permit(:person_id, :cooked, :salary)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food_type_id, :noun, :description, :cost)
    end
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
  before_action :set_waiter, only: [:show, :edit, :update, :destroy]

  # GET /waiters
  # GET /waiters.json
  def index
    @waiters = Waiter.all
  end

  # GET /waiters/1
  # GET /waiters/1.json
  def show
  end

  # GET /waiters/new
  def new
    @waiter = Waiter.new
  end

  # GET /waiters/1/edit
  def edit
  end

  # POST /waiters
  # POST /waiters.json
  def create
    @waiter = Waiter.new(waiter_params)

    respond_to do |format|
      if @waiter.save
        format.html { redirect_to @waiter, notice: 'Waiter was successfully created.' }
        format.json { render :show, status: :created, location: @waiter }
      else
        format.html { render :new }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiters/1
  # PATCH/PUT /waiters/1.json
  def update
    respond_to do |format|
      if @waiter.update(waiter_params)
        format.html { redirect_to @waiter, notice: 'Waiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @waiter }
      else
        format.html { render :edit }
        format.json { render json: @waiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiters/1
  # DELETE /waiters/1.json
  def destroy
    @waiter.destroy
    respond_to do |format|
      format.html { redirect_to waiters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiter
      @waiter = Waiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiter_params
      params.require(:waiter).permit(:person_id, :clients, :salary, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/security_helper.rb
module SecurityHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/waiters/_form.html.erb
<%= form_for(@waiter) do |f| %>
  <% if @waiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waiter.errors.count, "error") %> prohibited this waiter from being saved:</h2>

      <ul>
      <% @waiter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :clients %><br>
    <%= f.number_field :clients %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.check_box :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waiters/edit.html.erb
<h1>Editing waiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @waiter %> |
<%= link_to 'Back', waiters_path %>

app/views/waiters/index.html.erb
<h1>Listing waiters</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Clients</th>
      <th>Salary</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waiters.each do |waiter| %>
      <tr>
        <td><%= waiter.person_id %></td>
        <td><%= waiter.clients %></td>
        <td><%= waiter.salary %></td>
        <td><%= waiter.state %></td>
        <td><%= link_to 'Show', waiter %></td>
        <td><%= link_to 'Edit', edit_waiter_path(waiter) %></td>
        <td><%= link_to 'Destroy', waiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waiter', new_waiter_path %>

app/views/waiters/new.html.erb
<h1>New waiter</h1>

<%= render 'form' %>

<%= link_to 'Back', waiters_path %>

app/views/waiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @waiter.person_id %>
</p>

<p>
  <strong>Clients:</strong>
  <%= @waiter.clients %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @waiter.salary %>
</p>

<p>
  <strong>State:</strong>
  <%= @waiter.state %>
</p>

<%= link_to 'Edit', edit_waiter_path(@waiter) %> |
<%= link_to 'Back', waiters_path %>